-- 1. User
create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    password varchar(100) not null,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    email varchar(100) not null,
    birth_date date,
    employment_date date
    );

-- 2. Project
create table if not exists projects (
    id identity primary key,
    title varchar(50) not null,
    description varchar(100) not null,
    start_date date,
    end_date date
    );

-- 3. Unit
create table if not exists units (
    id identity primary key,
    title varchar(50) not null,
    description varchar(100) not null,
    project_id bigint not null,
    foreign key (project_id) references projects(id)
    );

-- 4. Task
create table if not exists tasks (
    id identity primary key,
    task_name varchar(50) not null,
    description varchar(250) not null,
    unit_id bigint not null,
    user_id bigint,
    status varchar(50) not null,
    foreign key (unit_id) references units(id),
    foreign key (user_id) references users(id)
    );


-- 5. Workers_projects
create table if not exists workers_projects (
    user_id bigint not null,
    project_id bigint  not null,
    primary key (user_id, project_id),
    foreign key (user_id) references users(id),
    foreign key (project_id) references projects(id)
    );

